server:
  port: 8083
spring:
  application:
    name: inventory-service
  main:
    banner-mode: "off"
  cache:
    type: simple
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

inventory:
  topics:
    low-stock: inventory-low-stock

app:
  topics:
    inventory-events: inventory-events

resilience4j:
  circuitbreaker:
    instances:
      kafka:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
