spring:
  application:
    name: common-lib
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  database:
    name: ${TARGET_DB_NAME} // change every time
